"""
Context Generator - AI Context File Generation

Produces .cursorrules (Markdown) and system-map.json for AI assistants.
"""

import os
import json
import yaml
from datetime import datetime
from typing import Dict, List, Optional


class ContextGenerator:
    """Generates AI context files from infrastructure data."""
    
    # Port allocation standards
    PORT_STANDARDS = {
        '80, 443': 'Reverse Proxy (Traefik/Nginx)',
        '5432': 'PostgreSQL (Shared DB)',
        '6379': 'Redis (Shared Cache)',
        '8000-8999': 'Applicazioni Python/FastAPI',
        '3000-3999': 'Applicazioni Node.js',
        '9000-9099': 'Monitoring (Prometheus/Grafana)'
    }
    
    def __init__(self, infrastructure: Dict = None, data_path: str = "/var/lib/nhi"):
        """
        Initialize generator.
        
        Args:
            infrastructure: Pre-scanned infrastructure data (optional)
            data_path: Base path for NHI data
        """
        self.data_path = data_path
        self.context_path = os.path.join(data_path, 'context')
        self.infrastructure = infrastructure or self._load_infrastructure()
    
    def _load_infrastructure(self) -> Dict:
        """Load infrastructure from saved file."""
        infra_path = os.path.join(self.data_path, 'infrastructure.yaml')
        
        if os.path.exists(infra_path):
            with open(infra_path, 'r') as f:
                return yaml.safe_load(f)
        
        return {'resources': [], 'nodes': [], 'storage': [], 'network': {}}
    
    def _load_config(self) -> Dict:
        """Load NHI configuration."""
        config_path = os.path.join(self.data_path, 'config.yaml')
        
        if os.path.exists(config_path):
            with open(config_path, 'r') as f:
                return yaml.safe_load(f)
        
        return {}
    
    def generate_cursorrules(self) -> str:
        """
        Generate .cursorrules Markdown content.
        
        Returns:
            Markdown string for .cursorrules
        """
        config = self._load_config()
        resources = self.infrastructure.get('resources', [])
        timestamp = datetime.now().strftime('%Y-%m-%d %H:%M')
        
        # Build infrastructure table
        infra_table = self._build_infrastructure_table(resources)
        
        # Build services table (NEW in v1.1)
        services = self._load_services()
        services_table = self._build_services_table(services)
        
        # Build port standards table
        port_table = "\n".join([
            f"| {ports} | {service} |"
            for ports, service in self.PORT_STANDARDS.items()
        ])
        
        content = f"""# 🧠 NHI Operational Rules

> **Auto-generated:** {timestamp}
> **Full Methodology:** `_NHI/NHI_METHODOLOGY.md`

---

## 1. SSOT (Single Source of Truth)
⚠️ **NEVER guess IPs, ports, or service names.**

| Document | Purpose | Path |
|----------|---------|------|
| **GLOBAL_CONTEXT.md** | Logical architecture | Root of Projects |
| **NHI_METHODOLOGY.md** | Full operational rules | `_NHI/` |

**Before ANY remote operation:** Consult GLOBAL_CONTEXT.md first.

---

## 2. Project Structure
> **"Un progetto = Un LXC = Una cartella locale"**

| Location | Contains | Purpose |
|----------|----------|---------|
| `Z:\\...\\Projects\\<project>\\` | **DOCS ONLY** | `project_manifest.md`, architecture |
| `Y:\\`, `W:\\`, `X:\\` (RaiDrive) | **LIVE CODE** | Edit, debug, execution |

---

## 3. SSH Rules
- **User:** `ai-agent` (everywhere)
- **Method:** Key-based auth only
- **Pattern:**
  ```bash
  ssh ai-agent@<IP from GLOBAL_CONTEXT> "command"
  ```

---

## 4. Credentials
- **Vault:** `_NHI/ansible/secrets.vault.yml`
- **If you see plaintext passwords:** STOP. Notify user.

---

## 5. Development Workflow
1. **Context:** Read `GLOBAL_CONTEXT.md` in root
2. **Docs:** Check `Z:\\<project>\\project_manifest.md`
3. **Code:** Switch to mapped LXC drive (`W:\\`, etc.)
4. **Deploy:** SSH to restart services
5. **Verify:** Check logs (`journalctl`, `docker logs`)
6. **Update:** Reflect changes in `Z:\\` docs

---

## 6. Port Allocation Standards

| Porte | Servizio |
|-------|----------|
{port_table}

---

## 7. Infrastructure Map

{infra_table}

---

## 8. Deployed Services Registry

{services_table}

---

## 9. Credentials Access

- **Vault Location:** `/var/lib/nhi/secrets/`
- **Get credential:** `nhi vault get <path>` (e.g., `nhi vault get services.postgresql.password`)
- **Keys:** Master Key for disaster recovery, Host Key for infrastructure, Services Key for apps
- **NEVER hardcode passwords in code**

---

## 10. Deployment Checklist

Before completing ANY deployment, ensure:
- [ ] LXC/VM created and running
- [ ] Service installed and healthy
- [ ] Ports configured and accessible
- [ ] Manifest created: `nhi manifest create <service>`
- [ ] Context regenerated: runs automatically every hour

---

*Auto-generated by NHI-CORE v1.1 - {timestamp}*
"""
        return content
    
    def _load_services(self) -> List[Dict]:
        """Load service manifests from registry."""
        services_path = os.path.join(self.data_path, 'registry', 'services')
        services = []
        
        if os.path.exists(services_path):
            for manifest_file in os.listdir(services_path):
                if manifest_file.endswith('.yaml'):
                    manifest_path = os.path.join(services_path, manifest_file)
                    with open(manifest_path, 'r') as f:
                        data = yaml.safe_load(f)
                        if data:
                            services.append(data)
        
        return services
    
    def _build_services_table(self, services: List[Dict]) -> str:
        """Build markdown table from service manifests."""
        if not services:
            return "| Service | LXC | IP | Ports | Status |\n|---------|-----|----|-------|--------|\n| *No services registered* | - | - | - | - |"
        
        lines = ["| Service | LXC | IP | Ports | Status |", "|---------|-----|----|-------|--------|"]
        
        for svc in sorted(services, key=lambda x: x.get('vmid', 0)):
            name = svc.get('name', 'Unknown')
            vmid = svc.get('vmid', 'N/A')
            ip = svc.get('network', {}).get('ip', 'N/A')
            ports = ', '.join([str(p.get('port', '')) for p in svc.get('network', {}).get('ports', [])])
            if not ports:
                ports = '-'
            
            # Check checklist completion
            checklist = svc.get('checklist', {})
            all_done = all(checklist.values()) if checklist else False
            status = '✅' if all_done else '⚠️'
            
            lines.append(f"| {name} | {vmid} | {ip} | {ports} | {status} |")
        
        return "\n".join(lines)
    
    def _build_infrastructure_table(self, resources: List[Dict]) -> str:
        """Build markdown table from resources."""
        if not resources:
            return "| IP | Service | Type |\n|----|---------|------|\n| *No resources discovered* | - | - |"
        
        lines = ["| IP | Service | Type | Status |", "|----|---------|----|--------|"]
        
        for res in sorted(resources, key=lambda x: x.get('vmid', 0)):
            ip = res.get('ip', 'N/A') or 'N/A'
            name = res.get('name', 'Unknown')
            res_type = res.get('type', '').upper()
            status = res.get('status', 'unknown')
            status_emoji = '🟢' if status == 'running' else '🔴'
            
            lines.append(f"| {ip} | {name} | {res_type} | {status_emoji} {status} |")
        
        return "\n".join(lines)
    
    def generate_system_map(self) -> Dict:
        """
        Generate system-map.json content.
        
        Returns:
            Dictionary for JSON serialization
        """
        config = self._load_config()
        
        system_map = {
            'version': '1.0',
            'generated': datetime.now().isoformat(),
            'proxmox': {
                'host': config.get('proxmox', {}).get('host', 'unknown'),
                'port': config.get('proxmox', {}).get('port', 8006)
            },
            'nodes': self.infrastructure.get('nodes', []),
            'resources': self.infrastructure.get('resources', []),
            'storage': self.infrastructure.get('storage', []),
            'network': self.infrastructure.get('network', {}),
            'port_standards': self.PORT_STANDARDS
        }
        
        return system_map
    
    def generate(self):
        """Generate all context files."""
        os.makedirs(self.context_path, exist_ok=True)
        
        # Generate .cursorrules
        cursorrules_content = self.generate_cursorrules()
        cursorrules_path = os.path.join(self.context_path, '.cursorrules')
        with open(cursorrules_path, 'w', encoding='utf-8') as f:
            f.write(cursorrules_content)
        
        # Generate system-map.json
        system_map = self.generate_system_map()
        system_map_path = os.path.join(self.context_path, 'system-map.json')
        with open(system_map_path, 'w', encoding='utf-8') as f:
            json.dump(system_map, f, indent=2, ensure_ascii=False)
        
        return {
            'cursorrules': cursorrules_path,
            'system_map': system_map_path
        }
