"""
Context Generator - AI Context File Generation

Produces .cursorrules (Markdown) and system-map.json for AI assistants.
UPDATED v1.1: Generates dynamic .cursorrules that references JSON SSOT.
"""

import os
import json
import yaml
from datetime import datetime
from typing import Dict, List, Optional


class ContextGenerator:
    """Generates AI context files from infrastructure data."""
    
    PORT_STANDARDS = {
        '80, 443': 'Reverse Proxy (Traefik/Nginx)',
        '5432': 'PostgreSQL (Shared DB)',
        '6379': 'Redis (Shared Cache)',
        '8000-8999': 'Applicazioni Python/FastAPI',
        '3000-3999': 'Applicazioni Node.js',
        '9000-9099': 'Monitoring (Prometheus/Grafana)'
    }
    
    def __init__(self, infrastructure: Dict = None, data_path: str = "/var/lib/nhi"):
        self.data_path = data_path
        self.context_path = os.path.join(data_path, 'context')
        self.infrastructure = infrastructure or self._load_infrastructure()
    
    def _load_infrastructure(self) -> Dict:
        infra_path = os.path.join(self.data_path, 'infrastructure.yaml')
        if os.path.exists(infra_path):
            with open(infra_path, 'r') as f:
                return yaml.safe_load(f)
        return {'resources': [], 'nodes': [], 'storage': [], 'network': {}}
    
    def _load_config(self) -> Dict:
        config_path = os.path.join(self.data_path, 'config.yaml')
        if os.path.exists(config_path):
            with open(config_path, 'r') as f:
                return yaml.safe_load(f)
        return {}
    
    def generate_cursorrules(self) -> str:
        """
        Generate .cursorrules Markdown content.
        Uses the v1.1 Dynamic SSOT template.
        """
        timestamp = datetime.now().strftime('%Y-%m-%d %H:%M')
        
        content = f"""# 🧠 NHI Operational Rules

> **Philosophy**: Logic here, Data elsewhere.
> **Auto-generated**: {timestamp}

---

## 1. 🗺️ Context & Data Sources (Dynamic SSOT)
Instead of hardcoding IPs and ports, **ALWAYS** refer to the following files:

| Type | Path | Content |
|------|------|---------|
| **Infrastructure** | `n:/nhi-data/context/system-map.json` | **SSOT**. Nodes, LXC IPs, Ports, Resources. |
| **Config/Paths** | `n:/nhi-data/nhi/config.yaml` | Core paths (`/var/lib/nhi`), Backups, Auth. |
| **Methodology** | `_NHI/NHI_METHODOLOGY.md` | *Reference* for operational procedures. |
| **Project Docs** | `Z:\\...\\Projects\\<project>\\project_manifest.md` | Specific project architecture. |

> **RULE**: Before any operation involving an IP or Port, read `system-map.json`. Do NOT guess.

---

## 2. 🛡️ Verification Protocol (STRICT)
When requested to verify, test, or check logs:
1.  **NEVER ASSUME SUCCESS**: Exit code 0 is the only truth.
2.  **SHOW YOUR WORK**: Output the raw command result to the user.
3.  **NO SILENT FAILURE**: Report every error immediately.

---

## 3. 🔐 SSH & Credentials
- **User**: `ai-agent` (defined in `config.yaml`).
- **Auth**: Key-based only.
- **Secrets**: NEVER reading/writing plaintext passwords. Use Vault (`/var/lib/nhi/secrets/` or `nhi vault get`).

---

## 4. 🚀 Development Workflow
1.  **Read Context**: Load `system-map.json` to know the target IP.
2.  **Check Status**: Verify target LXC is `running` in `system-map.json`.
3.  **Connect**: SSH into the target IP using `ai-agent`.
4.  **Deploy/Edit**: Work on mapped drives (`W:\\` etc) or via SSH.
5.  **Verify**: Apply Protocol #2.

---

## 5. ⚠️ Emergency Fallback
If `system-map.json` is unreadable or missing:
1.  **STOP**.
2.  Notify the user.
3.  Do NOT revert to hardcoded guesses.

---
*Generated by NHI-CORE v1.1 Context Generator*
"""
        return content

    def generate_system_map(self) -> Dict:
        config = self._load_config()
        
        system_map = {
            'version': '1.1',
            'generated': datetime.now().isoformat(),
            'proxmox': {
                'host': config.get('proxmox', {}).get('host', 'unknown'),
                'port': config.get('proxmox', {}).get('port', 8006)
            },
            'nodes': self.infrastructure.get('nodes', []),
            'resources': self.infrastructure.get('resources', []),
            'storage': self.infrastructure.get('storage', []),
            'network': self.infrastructure.get('network', {}),
            'port_standards': self.PORT_STANDARDS
        }
        return system_map
    
    def generate(self):
        """Generate all context files."""
        os.makedirs(self.context_path, exist_ok=True)
        
        # Generate .cursorrules
        cursorrules_content = self.generate_cursorrules()
        cursorrules_path = os.path.join(self.context_path, '.cursorrules')
        with open(cursorrules_path, 'w', encoding='utf-8') as f:
            f.write(cursorrules_content)
        
        # Generate system-map.json
        system_map = self.generate_system_map()
        system_map_path = os.path.join(self.context_path, 'system-map.json')
        with open(system_map_path, 'w', encoding='utf-8') as f:
            json.dump(system_map, f, indent=2, ensure_ascii=False)
        
        return {
            'cursorrules': cursorrules_path,
            'system_map': system_map_path
        }
